/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BorrowRouteImport } from './routes/borrow'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as EarnIdRouteImport } from './routes/earn.$id'
import { Route as BorrowIdRouteImport } from './routes/borrow.$id'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowRoute = BorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/market/$id',
  path: '/market/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnIdRoute = EarnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EarnRoute,
} as any)
const BorrowIdRoute = BorrowIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BorrowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/borrow': typeof BorrowRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRouteWithChildren
  '/markets': typeof MarketsRoute
  '/swap': typeof SwapRoute
  '/borrow/$id': typeof BorrowIdRoute
  '/earn/$id': typeof EarnIdRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/borrow': typeof BorrowRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRouteWithChildren
  '/markets': typeof MarketsRoute
  '/swap': typeof SwapRoute
  '/borrow/$id': typeof BorrowIdRoute
  '/earn/$id': typeof EarnIdRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/borrow': typeof BorrowRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRouteWithChildren
  '/markets': typeof MarketsRoute
  '/swap': typeof SwapRoute
  '/borrow/$id': typeof BorrowIdRoute
  '/earn/$id': typeof EarnIdRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/borrow'
    | '/dashboard'
    | '/earn'
    | '/markets'
    | '/swap'
    | '/borrow/$id'
    | '/earn/$id'
    | '/market/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/borrow'
    | '/dashboard'
    | '/earn'
    | '/markets'
    | '/swap'
    | '/borrow/$id'
    | '/earn/$id'
    | '/market/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/borrow'
    | '/dashboard'
    | '/earn'
    | '/markets'
    | '/swap'
    | '/borrow/$id'
    | '/earn/$id'
    | '/market/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BorrowRoute: typeof BorrowRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EarnRoute: typeof EarnRouteWithChildren
  MarketsRoute: typeof MarketsRoute
  SwapRoute: typeof SwapRoute
  MarketIdRoute: typeof MarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow': {
      id: '/borrow'
      path: '/borrow'
      fullPath: '/borrow'
      preLoaderRoute: typeof BorrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/market/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn/$id': {
      id: '/earn/$id'
      path: '/$id'
      fullPath: '/earn/$id'
      preLoaderRoute: typeof EarnIdRouteImport
      parentRoute: typeof EarnRoute
    }
    '/borrow/$id': {
      id: '/borrow/$id'
      path: '/$id'
      fullPath: '/borrow/$id'
      preLoaderRoute: typeof BorrowIdRouteImport
      parentRoute: typeof BorrowRoute
    }
  }
}

interface BorrowRouteChildren {
  BorrowIdRoute: typeof BorrowIdRoute
}

const BorrowRouteChildren: BorrowRouteChildren = {
  BorrowIdRoute: BorrowIdRoute,
}

const BorrowRouteWithChildren =
  BorrowRoute._addFileChildren(BorrowRouteChildren)

interface EarnRouteChildren {
  EarnIdRoute: typeof EarnIdRoute
}

const EarnRouteChildren: EarnRouteChildren = {
  EarnIdRoute: EarnIdRoute,
}

const EarnRouteWithChildren = EarnRoute._addFileChildren(EarnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BorrowRoute: BorrowRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EarnRoute: EarnRouteWithChildren,
  MarketsRoute: MarketsRoute,
  SwapRoute: SwapRoute,
  MarketIdRoute: MarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
